Resources/doc/reference/breadcrumb.rst
=> Grammar and missing ;

Seo/SeoPage.php, Tests/Seo/SeoPageTest.php
I've added some functions, to check whether a meta data has been set and some functions, to remove meta datas.
I wasn't sure whether I should add these function to the interface, as there might be other implementations which might break. What do you think?
=> has-functions for all attributes on a SeoPage and functions to remove metas

Resources/doc/reference/installation.rst
Had the same issue as described in #86.
I followed the installation guide, so I think this should fix the problem for others.
=> re-arrange default key under page. refs #86

Block/Breadcrumb/BaseBreadcrumbMenuBlockService.php, Block/Social/EmailShareButtonBlockService.php, Block/Social/FacebookLikeBoxBlockService.php, Block/Social/FacebookLikeButtonBlockService.php, Block/Social/FacebookSendButtonBlockService.php, Block/Social/FacebookShareButtonBlockService.php, Block/Social/PinterestPinButtonBlockService.php, Block/Social/TwitterEmbedTweetBlockService.php, Block/Social/TwitterFollowButtonBlockService.php, Block/Social/TwitterHashtagButtonBlockService.php, Block/Social/TwitterMentionButtonBlockService.php, Block/Social/TwitterShareButtonBlockService.php
=> Fix deprecated settings method on block service, fix #96

Block/Social/TwitterEmbedTweetBlockService.php
They are already shown in help messages.
Ref https://github.com/sonata-project/SonataSeoBundle/pull/109
=> Removed TwitterEmbedTweetBlockService comments

CHANGELOG.md, Seo/SeoPage.php, Seo/SeoPageInterface.php, UPGRADE-3.0.md
This will be a bc, but I think it's better to have all public methods in the interface.
=> Moved method definition to interface

UPGRADE-3.0.md, composer.json
Reverts sonata-project/SonataSeoBundle#163
=> Revert "Remove internal test classes from autoloader"

Resources/translations/SonataSeoBundle.it.xliff
Add missing italian translations.
=> Add missing italian translations

Command/SitemapGeneratorCommand.php, phpunit.xml.dist
I am targeting this branch, because this is pedantic.
I think coverage is not calculated correctly, lets see
=> Remove exceptions from phpunit whitelist

src/Resources/translations/SonataSeoBundle.ru.xliff
=> Added Russian translations

src/Resources/config/blocks.xml, src/Resources/config/services.xml
```markdown
- make services explicit public
```
This patch is needed for sf 4.
=> Make services public

docs/reference/breadcrumb.rst
I am targeting this branch, because this is docs.
Docs about custom breadcrumb was outdated.
=> Update docs about custom breadcrumb

src/DependencyInjection/SonataSeoExtension.php
```markdown
- Make `sonata.seo.page` alias public
```
=> Make alias public

docs/reference/installation.rst, docs/reference/social_blocks.rst, docs/reference/usage.rst
I am targeting this branch, because this is related to the docs.
Just a doc update
=> Updated docs

.gitattributes, .github/ISSUE_TEMPLATE/Bug.md, .github/ISSUE_TEMPLATE/Feature.md, .php_cs.dist, .travis.yml, .travis/before_script_test.sh, CONTRIBUTING.md, docs/conf.py, docs/reference/breadcrumb.rst, docs/reference/installation.rst, docs/reference/sitemap.rst, docs/reference/social_blocks.rst, docs/reference/usage.rst, src/DependencyInjection/Configuration.php
=> Manual merge

composer.json, src/Command/SitemapGeneratorCommand.php, src/Resources/config/services.xml, src/Sitemap/SourceManager.php
```markdown
- Added support for latest exporter
```
=> Added support for latest exporter

.github/workflows/qa.yml, phpstan.neon.dist, src/Seo/SeoPageInterface.php
Improve code quality by running phpstan 🚀 
I am targeting this branch, because this is BC, but should only be done for the next major version.
=> Added phpstan checks

src/Command/SitemapGeneratorCommand.php
Fixed error while generating sitemap.
Fixes #364
```markdown
- Compatibility of the sitemap generator command with Symfony 5
```
=> Fixed error while generating sitemap.

docs/reference/sitemap.rst
Replaced `permalink` to `url`
Force casted `lastmod` to DATETIME
Example from page https://github.com/sonata-project/SonataSeoBundle/blob/master/docs/reference/sitemap.rst
=> Fix example

docs/reference/sitemap.rst
=> Format documenation

.travis.yml, composer.json, src/DependencyInjection/Configuration.php, tests/Block/Breadcrumb/BreadcrumbTest.php, tests/Block/Social/FacebookLikeBoxBlockServiceTest.php, tests/Block/Social/FacebookLikeButtonBlockServiceTest.php, tests/Block/Social/FacebookSendButtonBlockServiceTest.php, tests/Block/Social/FacebookShareButtonBlockServiceTest.php, tests/Block/Social/TwitterEmbedTweetBlockServiceTest.php
I am targeting this branch, because this does not contain BC break
```markdown
- Bump SF to 4.4
```
=> Bump to SF 4.4

.travis.yml, composer.json, src/Block/Breadcrumb/BaseBreadcrumbMenuBlockService.php, src/Block/Breadcrumb/HomepageBreadcrumbBlockService.php, src/Block/Social/BaseFacebookSocialPluginsBlockService.php, src/Block/Social/BaseTwitterButtonBlockService.php, src/Block/Social/EmailShareButtonBlockService.php, src/Block/Social/FacebookLikeBoxBlockService.php, src/Block/Social/FacebookLikeButtonBlockService.php, src/Block/Social/FacebookSendButtonBlockService.php, src/Block/Social/FacebookShareButtonBlockService.php, src/Block/Social/PinterestPinButtonBlockService.php, src/Block/Social/TwitterEmbedTweetBlockService.php, src/Block/Social/TwitterFollowButtonBlockService.php, src/Block/Social/TwitterHashtagButtonBlockService.php, src/Block/Social/TwitterMentionButtonBlockService.php, src/Block/Social/TwitterShareButtonBlockService.php, src/Event/BreadcrumbListener.php, src/Resources/config/blocks.xml, tests/Block/Breadcrumb/BreadcrumbTest.php, tests/Block/Social/FacebookLikeBoxBlockServiceTest.php, tests/Block/Social/FacebookLikeButtonBlockServiceTest.php, tests/Block/Social/FacebookSendButtonBlockServiceTest.php, tests/Block/Social/FacebookShareButtonBlockServiceTest.php, tests/Block/Social/TwitterEmbedTweetBlockServiceTest.php
I am targeting this branch, because the parent class is changed and it cannot be done without breaking BC.
```markdown
- Bump block-bundle dependency
- Changed parent class of all block / breadcrumb services
```
=> Bump block-bundle dependency

src/Resources/config/blocks.xml
I am targeting this branch, because this is a bugfix for the next major release.
```markdown
- Fix service arguments of `PinterestPinButtonBlockService` and `HomepageBreadcrumbBlockService`
```
=> Fix service arguments

src/Resources/translations/SonataSeoBundle.nl.xliff
updates Dutch translations
I am targeting this branch, because updates a translation.
```markdown
- Updates Dutch translations
```
=> updates Dutch translations

src/Block/Breadcrumb/BaseBreadcrumbMenuBlockService.php, src/Block/Breadcrumb/HomepageBreadcrumbBlockService.php, src/Block/Social/BaseFacebookSocialPluginsBlockService.php, src/Block/Social/BaseTwitterButtonBlockService.php, src/Block/Social/EmailShareButtonBlockService.php, src/Block/Social/FacebookLikeBoxBlockService.php, src/Block/Social/FacebookLikeButtonBlockService.php, src/Block/Social/FacebookSendButtonBlockService.php, src/Block/Social/FacebookShareButtonBlockService.php, src/Block/Social/PinterestPinButtonBlockService.php, src/Block/Social/TwitterEmbedTweetBlockService.php, src/Block/Social/TwitterFollowButtonBlockService.php, src/Block/Social/TwitterHashtagButtonBlockService.php, src/Block/Social/TwitterMentionButtonBlockService.php, src/Block/Social/TwitterShareButtonBlockService.php, src/Command/SitemapGeneratorCommand.php, src/DependencyInjection/Compiler/BreadcrumbBlockServicesCompilerPass.php, src/DependencyInjection/Configuration.php, src/DependencyInjection/SonataSeoExtension.php, src/Seo/SeoPage.php, src/Seo/SeoPageInterface.php, src/Sitemap/SourceManager.php, src/SonataSeoBundle.php, src/Twig/Extension/SeoExtension.php
```markdown
- Added generic information to `SeoPageInterface`
- Soft move methods to `SeoPageInterface` using @method
```
=> Update phpdoc 

composer.json, src/Block/Breadcrumb/BaseBreadcrumbMenuBlockService.php, src/Block/Breadcrumb/HomepageBreadcrumbBlockService.php, src/Block/Social/FacebookLikeButtonBlockService.php, src/Block/Social/FacebookShareButtonBlockService.php, src/Block/Social/TwitterEmbedTweetBlockService.php, src/BreadcrumbInterface.php, src/Command/SitemapGeneratorCommand.php, src/DependencyInjection/SonataSeoExtension.php, src/Event/BreadcrumbListener.php, src/Twig/Extension/SeoExtension.php
Add type hints and change visibility to private in final classes.
I am targeting this branch, because these change should be done in this branch
=> Add type hints
