Resources/doc/reference/twig_helpers.rst, Seo/SeoPage.php, Seo/SeoPageInterface.php, Tests/Twig/Extension/SeoExtensionTest.php, Twig/Extension/SeoExtension.php
Added support for [oEmbed](http://www.oembed.com/) which is used to embed rich content by platforms like [wordpress](http://codex.wordpress.org/Embeds#oEmbed)
=> Added oEmbed support

DependencyInjection/Configuration.php, DependencyInjection/SonataSeoExtension.php, Tests/DependencyInjection/ConfigurationTest.php, Tests/DependencyInjection/data/config.yml
This pull request:
- Makes it possible to split the sonata_seo configs over multiple config files
- Makes ``app/console config:dump-reference SonataSeoBundle`` work (fixes #59)
I tested with the config from http://sonata-project.org/bundles/seo/master/doc/reference/usage.html
AFAIK this pull request is BC but if that is not the case please let me know so I can fix that.
=> Use the configuration class for the bundle config

Resources/views/Block/_twitter_sdk.html.twig
block name was wrong in twig template. It worked like it should but you cannot override the block correctly.
=> Fix twitter sdk twig block name

Resources/doc/reference/installation.rst
According to this, the default key should be underneath page, right? 
https://github.com/sonata-project/SonataSeoBundle/blob/master/DependencyInjection/Configuration.php#L26
=> Fix bundle config example in docs

DependencyInjection/SonataSeoExtension.php, Tests/DependencyInjection/SonataSeoExtensionTest.php
After installing SonataSeoBundle in our project, this error popped out :
`The service "sonata.seo.block.breadcrumb.homepage" has a dependency on a non-existent service "knp_menu.menu_provider".`
Actually, KnpMenuBundle is also needed to load the `blocks.xml` file so, since it's optional, it's probably better to avoid to load that file than to add a new dependency.
=> Avoided blocks.xml loading when KnpMenuBundle is missing #56

Block/Breadcrumb/BaseBreadcrumbMenuBlockService.php
The 'context' setting is missing in the breadcrumb service. This could be an error when rendering the breadcrumb using "sonata_block_render_event".
This would also throw an exception in https://github.com/sonata-project/SonataBlockBundle/blob/master/Block/BlockContextManager.php#L259 because the 'context' setting is unknown.
Please check these pr's as well
=> Context is missing in breadcrumb service

UPGRADE-3.0.md, composer.json
I am targetting this branch, because some bundles use the test classes.
Related to https://github.com/sonata-project/dev-kit/issues/179
```markdown
- internal test classes are now excluded from the autoloader
```
Tests for internal components shouldn't be loaded in production or extended by other bundles.
=> Remove internal test classes from autoloader

Resources/doc/reference/installation.rst
I am targetting this branch, because this is BC.
remove duplicate key `default` in installation docs
=> removed duplicate key in docs

Resources/views/Block/breadcrumb.html.twig
I am targetting this branch, because this is a patch.
```markdown
- Added support for `safe_label` in breadcrumb
- Added support for `false` translation in breadcrumb
```
Added support for `safe_label` to display raw html and `translation_domain: false` to disable translation.
=> Added support for disabled translation in breadcrumb

Block/Social/TwitterEmbedTweetBlockService.php, Sitemap/SourceManager.php, Tests/Block/Social/TwitterEmbedTweetBlockServiceTest.php
I am targetting this branch, because this is BC.
Only a PHP Doc fix
=> removed useless class comment

Twig/Extension/SeoExtension.php, UPGRADE-2.x.md
I am targetting this branch, because this is BC.
```markdown
- `Sonata\SeoBundle\Twig\Extension::renderTitle()` in favor of `Sonata\SeoBundle\Twig\Extension::getTitle()`
- `Sonata\SeoBundle\Twig\Extension::renderMetadatas()` in favor of `Sonata\SeoBundle\Twig\Extension::getMetadatas()`
- `Sonata\SeoBundle\Twig\Extension::renderHtmlAttributes()` in favor of `Sonata\SeoBundle\Twig\Extension::getHtmlAttributes()`
- `Sonata\SeoBundle\Twig\Extension::renderHeadAttributes()` in favor of `Sonata\SeoBundle\Twig\Extension::getHeadAttributes()`
- `Sonata\SeoBundle\Twig\Extension::renderLinkCanonical()` in favor of `Sonata\SeoBundle\Twig\Extension::getLinkCanonical()`
- `Sonata\SeoBundle\Twig\Extension::renderLangAlternates()` in favor of `Sonata\SeoBundle\Twig\Extension::getLangAlternates()`
```
=> better deprecation handling for methods in SeoExtension

Block/Social/TwitterEmbedTweetBlockService.php
I am targetting this branch, because this is a bugfix.
```markdown
- Default value for `lang` to `null `instead of array of languages
```
=> Fix wrong default value form option for sonata.seo.block.twitter.embed block

Block/Social/BaseFacebookSocialPluginsBlockService.php, Block/Social/BaseTwitterButtonBlockService.php, Block/Social/EmailShareButtonBlockService.php, Block/Social/PinterestPinButtonBlockService.php, composer.json
I am targetting this branch, because this is BC.
```markdown
- use `Sonata\BlockBundle\Block\Service\AbstractAdminBlockService` instead of deprecated `Sonata\BlockBundle\Block\BaseBlockService`
```
=> use Sonata\BlockBundle\Block\Service\AbstractAdminBlockService instead of deprecated Sonata\BlockBundle\Block\BaseBlockService

composer.json
I am targeting this branch, because this should be backwards compatible.
```markdown
- Change twig/twig composer.requirement to allow `^2.0`
```
Will allow twig 2.0 when using the SonataSeoBundle
=> allow twig ^2.0

Tests/DependencyInjection/ConfigurationTest.php, Tests/DependencyInjection/SonataSeoExtensionTest.php, Tests/Helpers/PHPUnit_Framework_TestCase.php, Tests/Seo/SeoPageTest.php, Tests/Twig/Extension/SeoExtensionTest.php
=> use createMock instead of deprecated getMock()

Resources/views/Block/breadcrumb.html.twig, composer.json
I am targeting this branch, because branch 2.x supports Twig 2.
```markdown
- `SonataSeoBundle/Resources/views/Block/breadcrumb.html.twig` changed "sameas" in "same as"
```
In twig 2 "sameas" bacames "same as" ( https://twig.sensiolabs.org/doc/2.x/tests/sameas.html)
"same as" works also in in Twig 1 because it is an alias of "sameas" (https://twig.sensiolabs.org/doc/1.x/tests/sameas.html)
=> Fix for Twig 2

src/Block/Social/TwitterEmbedTweetBlockService.php
I am targetting this branch, because this is a bugfix.
Closes #185
```markdown
- Pass the right option for showing form help in twitter embedded block
```
=> Fix wrong help_block form option for sonata.seo.block.twitter.embed block

UPGRADE-2.x.md, composer.json
I am targeting this branch, because  the optional dependency was added here.
```markdown
- moved `sonata-project/block-bundle` back to require-dev
```
When block-bundle is required it forces me also to set a configuration for `sonata_block.default_context`. As the block usage is optional we should move this requiredment back to require-dev
=> move block-bundle back to require-dev

composer.json, src/DependencyInjection/SonataSeoExtension.php
```markdown
- Support for old versions of PHP and Symfony.
```
=> Drop old versions of php/sf

src/Block/Social/EmailShareButtonBlockService.php, src/Block/Social/FacebookLikeBoxBlockService.php, src/Block/Social/FacebookLikeButtonBlockService.php, src/Block/Social/FacebookSendButtonBlockService.php, src/Block/Social/FacebookShareButtonBlockService.php, src/Block/Social/PinterestPinButtonBlockService.php, src/Block/Social/TwitterEmbedTweetBlockService.php, src/Block/Social/TwitterFollowButtonBlockService.php, src/Block/Social/TwitterHashtagButtonBlockService.php, src/Block/Social/TwitterMentionButtonBlockService.php, src/Block/Social/TwitterShareButtonBlockService.php
```markdown
- Removed BC layer for old symfony versions
```
=> Removed symfony BC layer for old symfony versions

composer.json, src/Block/Breadcrumb/BaseBreadcrumbMenuBlockService.php
I am targeting this branch, because this is deprecated on this branch.
Closes #238
```markdown
- do not use deprecated array for block menu service
```
See #238
=> do not use deprecated array for block menu service

src/DependencyInjection/Configuration.php, tests/DependencyInjection/ConfigurationTest.php
I am targeting this branch, because this is a bugfix.
```markdown
- Changed default title to `Project name`
```
There's no reason for `Sonata Project` as the default SEO title.
=> Removed default title

src/DependencyInjection/SonataSeoExtension.php, src/Resources/config/commands.xml
I am targeting this branch, because there is no BC-break.
I am adding this code because the command is not automatically registered.
```markdown
+ Register `Sonata\SeoBundle\Command\SitemapGeneratorCommand` via `console.command` tag
```
=> Register Symfony Command

composer.json, docs/reference/social_blocks.rst, src/Block/Breadcrumb/BaseBreadcrumbMenuBlockService.php, src/Block/Social/EmailShareButtonBlockService.php, src/Block/Social/FacebookLikeBoxBlockService.php, src/Block/Social/FacebookLikeButtonBlockService.php, src/Block/Social/FacebookSendButtonBlockService.php, src/Block/Social/FacebookShareButtonBlockService.php, src/Block/Social/PinterestPinButtonBlockService.php, src/Block/Social/TwitterEmbedTweetBlockService.php, src/Block/Social/TwitterFollowButtonBlockService.php, src/Block/Social/TwitterHashtagButtonBlockService.php, src/Block/Social/TwitterMentionButtonBlockService.php, src/Block/Social/TwitterShareButtonBlockService.php, src/Resources/config/blocks.xml
```markdown
- Switch all templates references to Twig namespaced syntax
- Switch from templating service to sonata.templating
```
This PR is a part of a big plan of decoupling sonata-project bundles from Templating Component. See sonata-project/dev-kit#380 for details
=> Decouple from Templating Component, Stage 1

composer.json
Trying to fix travis timeout with requiring very last version of `guzzle/guzzle`
=> Require very last version of guzzle/guzzle

docs/reference/usage.rst, src/Seo/SeoAwareTrait.php
I am targeting this branch, because this is a new feature.
```markdown
- Added `SeoAwareTrait`
```
This trait can be used the same way as the `LoggerAwareTrait`, `ContainerAwareTrait`, ...
=> Created SeoAwareTrait

src/Seo/SeoPage.php
Closes #{put_issue_number_here}
```markdown
- Initialized `SeoPage::$htmlAttributes` with empty array
```
According to the PHPDoc, the value should always return an array.
=> Fixed possible null error in SeoPage

src/DependencyInjection/Compiler/ServiceCompilerPass.php, src/DependencyInjection/SonataSeoExtension.php, src/SonataSeoBundle.php
I am targeting this branch, because this is a bugfix.
```markdown
- Allow overriding default seo service
```
Now you can override the default seo service outside the seo bundle scope:
```yaml
sonata_seo:
page:
default 'acme.seo.page'
```
=> Allow overriding default seo service

src/DependencyInjection/Compiler/ServiceCompilerPass.php, tests/DependencyInjection/Compiler/ServiceCompilerPassTest.php, tests/Stubs/SeoPageStub.php
Added the `SeoPageInterface` as an alias in the container. This way developers can use Dependency Injection to grab the SeoPage class they configured in their configuration. 
The `SeoPageInterface` wil always be the instance which is configured in the `sonata_seo.page.default` setting.
I am targeting this branch, because it's a new feature.
Closes #320 
```markdown
- Added `SeoPageInterface` as alias service of `sonata.seo.page` for Dependency Injection usages.
```
=> Added the SeoPageInterface to the container as an alias.

src/Twig/Extension/SeoExtension.php, tests/Twig/Extension/SeoExtensionTest.php
Strict types were added in the latest version (#313), which causes metadata values to not be implicitly converted to strings anymore.
Most notably what I picked up is the [currency in the ProductBundle](https://github.com/sonata-project/ecommerce/blob/2.x/src/ProductBundle/Seo/Services/Facebook.php#L96) which is an object (containing a `__toString` method) and the [image dimensions for a product](https://github.com/sonata-project/ecommerce/blob/2.x/src/ProductBundle/Seo/Services/Facebook.php#L113-L114) which are integers.
I am targeting this branch, because it is a bug fix introduced in the latest stable version.
```markdown
- cast metadata to string during render
```
=> Cast metadata to string

src/Seo/SeoPage.php, tests/Seo/SeoPageTest.php
This is a follow-up to #330, to deprecate passing non-string values for meta content.
```markdown
- passing a non-string value when adding meta content
```
=> Deprecate passing non-string meta content

composer.json, src/Twig/Extension/SeoExtension.php
Fixing Twig deprecation notice in Symfony 4
```markdown
* deprecation notice about using namespaced classes from `\Twig\`
```
=> Twig deprecation notice

docs/reference/sitemap.rst, src/Command/SitemapGeneratorCommand.php, src/Resources/config/commands.xml
Removed deprecation notice: "Symfony\Bundle\FrameworkBundle\Command\ContainerAwareCommand" class is deprecated
https://symfony.com/blog/new-in-symfony-4-2-important-deprecations#deprecated-containerawarecommand
I am targeting this branch, because this upgrade is compatible with Symfony >=2.8, mentioned as lowest in composer.json. 
Closes #344 
```markdown
- If you extend SitemapGeneratorCommand, avoid usage of the container in the child command declarations.
- Fixed deprecation notice: "Symfony\Bundle\FrameworkBundle\Command\ContainerAwareCommand" class is deprecated
```
=> Removed deprecation notice about ContainerAwareCommand

composer.json, src/Resources/views/Block/_facebook_sdk.html.twig, src/Resources/views/Block/_pinterest_sdk.html.twig, src/Resources/views/Block/_twitter_sdk.html.twig, src/Resources/views/Block/block_email_share_button.html.twig, src/Resources/views/Block/block_facebook_like_box.html.twig, src/Resources/views/Block/block_facebook_like_button.html.twig, src/Resources/views/Block/block_facebook_send_button.html.twig, src/Resources/views/Block/block_facebook_share_button.html.twig, src/Resources/views/Block/block_pinterest_pin_button.html.twig, src/Resources/views/Block/block_twitter_embed.html.twig, src/Resources/views/Block/block_twitter_follow_button.html.twig, src/Resources/views/Block/block_twitter_hashtag_button.html.twig, src/Resources/views/Block/block_twitter_mention_button.html.twig, src/Resources/views/Block/block_twitter_share_button.html.twig, src/Resources/views/Block/breadcrumb.html.twig
I am targeting this branch, because it has no effect for the end user, except fixing some deprecations with more recent Twig versions.
Closes #339 
```markdown
- Fixed use of deprecated `spaceless` Twig tag
```
=> Bump Twig to 1.40|2.9 and replace deprecated spaceless tags with apply spaceless filter

composer.json, src/DependencyInjection/SonataSeoExtension.php, tests/DependencyInjection/ConfigurationTest.php
This is the same thing as https://github.com/sonata-project/SonataAdminBundle/pull/5733, dropping support of Symfony < 3.4 and >= 4, < 4.2
I am targeting this branch, because these changes respect BC.
```markdown
- Support for Symfony < 3.4
- Support for Symfony >= 4, < 4.2
```
=> Dropping support for symfony < 3.4

composer.json
I guess this one is self explanatory...
I am targeting this branch, because it only adds support for newer versions of Twig and Symfony.
Closes #353
```markdown
- Support for Twig 3 and Symfony 5
```
=> Add support for Symfony 5 and Twig 3

UPGRADE-2.x.md, composer.json, docs/reference/social_blocks.rst, src/Block/Social/TwitterEmbedTweetBlockService.php, src/DependencyInjection/Configuration.php, src/DependencyInjection/SonataSeoExtension.php, src/Resources/config/blocks.xml, tests/DependencyInjection/ConfigurationTest.php
I am targetting this branch, because this adds a new implementation without removing the existing one. This is a rework of #161, but targets the psr http-client.
``` markdown
- Added support for `psr/http-client` in `TwitterEmbedTweetBlockService`
```
Added support for an abstract http client without removing the existing old guzzle implementation.
=> Deprecate Guzzle with psr http-client

src/Block/Breadcrumb/BaseBreadcrumbMenuBlockService.php, src/BreadcrumbInterface.php, src/Event/BreadcrumbListener.php
There is no commen interface for breadcrumbs yet. A breadcrumb must implement a `handleContext` method.
I am targeting this branch, because this feature is BC.
```markdown
- Added new `BreadcrumbInterface`
```
=> Create new Breadcrumb interface

src/Block/Breadcrumb/BaseBreadcrumbMenuBlockService.php, tests/Block/Breadcrumb/BreadcrumbTest.php
The Pull Request suggest a fix that correct a parameter type problem. Indeed, a string is given instead of a boolean.
I am targeting this branch, because the fix is BC. The SonataSeoBundle 2.x version needs at least php7.2 which contains parameter types on methods.
Closes #419
```markdown
- Fix parameter type when calling knp menu
```
=> fix_knp_menu_type_error

composer.json
Fix to issue #540
Fix block bundle requirement
I am targeting this branch, because it is a clarification of an already-existing dependency, rather than a breaking change. (Currently, if a block bundle outside of the range I'm specifying is installed, the SEO bundle malfunctions. So this is a clarification, rather than something that significantly changes existing behavior.)
Closes #540.
Commit one: Changed composer.json. Removed conflict listing and dev dependency, since the block bundle is now listed as a main dependency.
Commit two: Updated composer.json. Bumped block bundle version requirement from ^3.11 to ^3.17 in order to fix a missing test case.
=> Specify block bundle versions

composer.json
Supports #576 
The dependency is required for this: https://github.com/sonata-project/SonataSeoBundle/blob/322d6c782116ece88c4df16e0de4bb68bae743e4/tests/DependencyInjection/SonataSeoExtensionTest.php#L16
=> Add missing test dependency
